services:
  - type: web
    name: wealthpulse-backend
    env: python
    region: mumbai
    buildCommand: 
      - chmod +x render-build.sh
      - ./render-build.sh
    startCommand: gunicorn app:app --workers 4 --timeout 30 --bind 0.0.0.0:$PORT
    envVars:
      - key: DEEPSEEK_API_KEY
        value: ${DEEPSEEK_API_KEY}
      - key: ENCRYPTION_KEY
        value: ${ENCRYPTION_KEY}
      - key: REDIS_URL
        value: ${REDIS_INTERNAL_URL}
      - key: AI_FAILURE_THRESHOLD
        value: "3"
      - key: FLASK_ENV
        value: production
